# This is a basic workflow to help you get started with Actions
# .github/workflows/norminette.yml
name: norminettev2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  norminette_v2_job:
    runs-on: ubuntu-latest
    name: norminette v2
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v2
      with:
        flags: 'src'
